### PR TITLE
Redesign: 💙 blue   

### PR DESCRIPTION
**Pull request by stefanb**
Opening this instead of #89.

### CODE REVIEW

**Comment by stefanb** [comment]
At some resolutions the map element is too high, pushing attribution out of view, dejavu of #86 & #88, eg iPhone 5/SE:
image

**Review by jalezi — COMMENTED** [review]
@stefanb 'accepts' color I fixed in 31a44ab426000ac18ba7827c5d1bc89b2594c36b . I guess it was lost with merging.

**Comment by jalezi** [comment]
Screenshot 2021-12-16 13 56 40
Screenshot 2021-12-16 13 55 27
Screenshot 2021-12-16 13 53 43
Screenshot 2021-12-16 13 53 01
Screenshot 2021-12-16 13 52 13
Screenshot 2021-12-16 14 01 20

**Review by miaerbus — APPROVED** [review]
I really like this and would merge it asap :)

**Review by lukarenko — APPROVED** [review]
This is great work! Just merge!

**Comment by lukarenko** [comment]
@jalezi minor bug: when in Card view, go to Doctor page, when Back to list it switches to Map view (and not previous Card view)

**Comment by jalezi** [comment]
> @jalezi minor bug: when in Card view, go to Doctor page, when Back to list it switches to Map view (and not previous Card view)

Yup, aware of the problem. I will fixed with not navigating to doctor page. I think @stefanb mentioned somewhere that it would be good not to. Can not decide how to implement yet. I guess the easiest way is with modal. 

Also when switching between map and cards filter/map state is lost.

**Pull request merged**
