### PR TITLE
Hide inactive text on inactive sub filter on md breakpoint

### PR DESCRIPTION
**Pull request by TadejPolajnar**
Issue: https://github.com/sledilnik/zdravniki/issues/184

~~As Luka suggested [here](https://github.com/sledilnik/zdravniki/issues/184#issuecomment-1003365058), breakpoint is now changed from `lg` to `xl`:~~

Text of inactive subfilter is now hidden on smaller screens (>1200<1536px) and fully visible on larger screens (>1536px).
image

### CODE REVIEW

**Comment by lukarenko** [comment]
This is OK for me, but I will let @bananica to decide

**Comment by lukarenko** [comment]
@TadejPolajnar is it possible to keep labels for doctor type, but hide it for subtype and/or accepts/rejects only first?

**Comment by TadejPolajnar** [comment]
> @TadejPolajnar is it possible to keep labels for doctor type, but hide it for subtype and/or accepts/rejects only first?

@lukarenko Sure, will fix it asap 🙂

**Comment by lukarenko** [comment]
@TadejPolajnar this one is still problematic, maybe hive also Accepts/Rejects texts in such case
image

**Comment by lukarenko** [comment]
Perfect!

**Comment by TadejPolajnar** [comment]
@lukarenko should be fine now :) 
If the screen is less than 1200px width
image

If the screen is between 1200px and<1536px
image

And if the screen is wider than 1536px
image

**Pull request merged**
