### PR TITLE
Fix/no institution

### PR DESCRIPTION
**Pull request by jalezi**
Begin: #175

Add dummy institution if doctor's institution not found/exists. Most `DUMMY_INST` properties are empty strings.

```
const DUMMY_INST = {
  unit: '',
  name: '',
  website: '',
  phone: '',
  lat: GEO_LOCATION.SL_CENTER[0],
  lon: GEO_LOCATION.SL_CENTER[1],
  address: '',
  city: '',
  post: '0000 Neznan',
  municipalityPart: '',
  municipality: '',
};
```

Doctor has new `bool` property `hasInstitution`. We can use this on dr's card to notify user that something is wrong.

We should also validate data on [zdravniki-data](https://github.com/sledilnik/zdravniki-data).

### CODE REVIEW

**Comment by lukarenko** [comment]
@jalezi does not work on my local test with this path (corrupted version):
https://raw.githubusercontent.com/sledilnik/zdravniki-data/1fa1c4d4393fbf4c2ae47d07b4d21d823bc63a8b/csv/doctors.csv
image

**Comment by jalezi** [comment]
remove /doctors.csv in base path.

**Comment by jalezi** [comment]
@lukarenko 

```
const BASE_PATH = '/sledilnik/zdravniki-data/main/csv';

const CORRUPTED_PATH = '/sledilnik/zdravniki-data/1fa1c4d4393fbf4c2ae47d07b4d21d823bc63a8b/csv';

const INSTITUTIONS_CSV_PATH = `${BASE_PATH}/institutions.csv`;
const DOCTORS_CSV_PATH = `${CORRUPTED_PATH}/doctors.csv`;
```

no `inst_id`
corrupted-path

And ofcourse doctor page is 404.

**Comment by lukarenko** [comment]
My bad, it works OK.

**Pull request merged**
