### PR TITLE
Use doctor overrides

### LINKED ISSUE #148: Overrides for ZZZS data
We are accepting corrections from doctors via GForms. After review of the feedback, we add overrides for ZZZS data in form of delta changes via [this table](https://docs.google.com/spreadsheets/d/1gsIkUsvO-2_atHTsU9UcH2q69Js9PuvskTbtuY3eEWQ/edit?resourcekey#gid=1427531019).

This data is then merged with `doctors.csv` into `doctors-overrides.csv` - here is example how data looks for some doctors with overrides:
image

Related issue on data: https://github.com/sledilnik/zdravniki-data/issues/8

How to implement overrides in the page:

- [x] `lat`, `lon`:
 * use these coordinates to position doctor on the map (instead of the ones in institution)

- [x] `note_override`, `accepts_override`: 
 * change accepts value
 * add note to tooltip (Glavarinski količnik: X, `note` Popravek od: 22. 12. 2021)  
 
- [x] `availability_override`: 
 * change value
 * add note to tooltip (Obstoječi tekst. Popravek od: 22. 12. 2021)

- [x] `address`, `post`, `phone`, `website`: 
 * change value (use this one instead of the one for institution)
 * include in search
 * add note to tooltip (Popravek od: 22. 12. 2021)

- [x] `email`: 
 * add email address to doctor card
 
- [x] `orderform`: 
 * add `Naročanje` button to doctor card

When new fields will be added, we will also need to change Report error form to also support adding email and order form and to put override note into note field

### PR DESCRIPTION
**Pull request by jalezi**
Partially fixes #148.

It should use new location, accepts_override, availability_override, etc.

Add note_override, date_override, email, orderform to doctor page. Needs styling.

### CODE REVIEW

**Comment by jalezi** [comment]
@stefanb si me prehitel :)

**Comment by jalezi** [comment]
If data is correct I would merge. Styling can be done later to avoid too many changes.

**Comment by stefanb** [comment]
Note that using "fixes #...." will fully resolve the mentioned ticket when merging, even if it has "Partially " before it.
https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by lukarenko** [comment]
@jalezi this was quick!
We should at least add note to tooltip of Accepts button if we use override, something like this:
```
Sprejema nove paciente.
Sprememba: 2021-12-23

Glavarinski količnik:
       1902,1
```
image

This way we will have note on all places (doctor card, doctor tooltip on map, doctor page).

**Comment by lukarenko** [comment]
@jalezi before merge, I would also change data processing to put everything to `doctors.csv` and we can make `doctors-overrides.csv` obsolete

Since we are changing this: can we also rename `dict-institiutions.csv` to `institutions.csv`? I can prepare changes on data side and then we make a switch.

**Comment by lukarenko** [comment]
Have renamed CSV. Production still works with overrides. Will remove old files later when this gets on production.

**Comment by lukarenko** [comment]
@bananica this needs some styling love from you:
- location of change date on doctor card
- styling of e-mail (see Strgar Hladnik Mihaela)
- styling of Naročanje button (see Zevnik Krištof)

**Review by lukarenko — APPROVED** [review]
I think this is good enough for now, we can improve styling in following days when more people see the overrides.

**Pull request merged**
