### PR TITLE
Fix: Map should fit better to Slovenia on initial load #96

### PR DESCRIPTION
**Pull request by jalezi**

### CODE REVIEW

**Comment by stefanb** [comment]
I don't think specifying a map zoom for specific breakpoints is the right approach, as it does not scale well, literally:
image
image
image
image

**Comment by jalezi** [comment]
I didn't try to set zoom for larger screens while I was not sure if it's the right approach :).

I have tried with fitbounds. Could not find good solution.

I guess it will have to wait while it might need more complex changes . I am not even sure if I am able to solve it without any help from more experienced react dev. 

For mobile landscape I am not sure if we can find satisfying solution at all. Maybe with new design (on mobile with map/cards switch) and hiding header the map height will be big enough. Not sure if we should pay attention at all or at least not ATM.

**Comment by jalezi** [comment]
Poor attempt.

**Comment by jalezi** [comment]
Poor attempt.

**Pull request closed without merging**
