### PR TITLE
Resolve PR confilicts

### PR DESCRIPTION
**Pull request by jalezi**
Yesterday @stefanb and I had short discussion about possible PR conflicts. We haven't made any decision.

This is just attempt to solve possible conflicts.

This PR includes: #67, #92, #81, #83

What I did: 

1. from master create new branch "develop"
2. merge #67 
3. slowly cherry pick each commit one by one from: #92, #81 and #83.

I’m not sure if it was right decision to include #81 while is still marked as draft, but #83 is based on it.

I skipped #88 while it solves issue #86 only partially and I guess it will be fixed with new design (#89).

Assuming I did everything right, the next step would be prepare PR with new design (#89). 

Any thoughts? Especially @mihaerzen, I don't know how far are you with prop-types.

### CODE REVIEW

**Comment by mihaerzen** [comment]
Hey! The prop types PR is not ready to be merged. I haven't had any time last week to work on it, unfortunately. Also, I would consider it non-blocking so go ahead and deploy without it. The prop-types I would almost consider a nice to have but not crucial for any of the functionalities. Let me know if think different. I can only say I will try to finish it by the end of this week.

**Comment by lukarenko** [comment]
Quick test report:
✅ page not found look good #67
❓ report error #72 - if we have it on doctor page, maybe we should also have button on search results for faster access to entry form. Should we have another free-form field to add a Note?
✅ preserve search state #83 - looks MVP ready!

In general I think we could merge changes/PRs faster and rebase WIP PR more often to reduce need to resolve conflicts on bigger merges.

**Comment by lukarenko** [comment]
@jalezi I suspect it is a merge bug that SPREJEMA stays red? Should be green, right?
image

**Comment by jalezi** [comment]
> In general I think we could merge changes/PRs faster and rebase WIP PR more often to reduce need to resolve conflicts on bigger merges.

I agree with @lukarenko. Smaller PRs, easier and faster review. I would include your PR @mihaerzen (basically it's one commit).  You can slowly fix warnings and maybe even I can give you a hand if I recognize something that is easy to fix (I have plenty of time). Also with each prop-type fix I would add appropriate test, which are desperately needed. As you say prop-types are not essential for functionality and I guess we can take time to fix.

Also I am pretty sure that there is still some useless code that I would like to refactor after we implement new design.

**Comment by jalezi** [comment]
@bananica I have also created [develop-blue-design](https://github.com/sledilnik/zdravniki/tree/develop-blue-design) branch, where I've (hopefully correct) resolved conflicts with this PR.

**Pull request merged**
