### PR TITLE
🛂 Add missing react prop types

### PR DESCRIPTION
**Pull request by mihaerzen**
This PR adds missing prop types and enables the `react/prop-types` eslint error mode.

### CODE REVIEW

**Comment by stefanb** [comment]
Changed target branch for clearer diff

**Comment by stefanb** [comment]
@mihaerzen I merged master into this branch to bring it up to speed and it seems that all the changes from this PR are already in the master from the follow-up PRs, hence 0 files changed in this PR, but there are still 10 leftover linter warnings to fix.

**Comment by mihaerzen** [comment]
This PR is finally ready for review @stefanb , @jalezi or anyone interested. ✌🏼

**Review by jalezi — APPROVED** [review]
It looks ok. :)

**Comment by mihaerzen** [comment]
@jalezi getting this error now:

image

Do you maybe know what is happening?

**Review by stefanb — APPROVED** [review]
Tnx, didn't know about `StylePropType`.

**Comment by jalezi** [comment]
> @jalezi getting this error now:
> 
> image
> 
> Do you maybe know what is happening?

Nope. @overlordtm ?

**Comment by mihaerzen** [comment]
@stefanb @jalezi should we merge this or wait for the error to be resolved?

**Comment by stefanb** [comment]
Checking if other PRs have the same problem

**Comment by stefanb** [comment]
Yup, https://github.com/sledilnik/zdravniki/pull/181 has the same problem

**Pull request merged**
