### PR TITLE
Basic FAQ subpage

### LINKED ISSUE #28: FAQ subpage
We would like to have FAQ subpage, similar as we have here for Sledilnik (done by @miaerbus): 
https://pr-983.preview.sledilnik.org/sl/faq-vaccines

We could enter all the FAQ texts into backend.sledilnik.org:
https://docs.google.com/document/d/1m2sDOBa9ht7rK8ZWDJdxydwd-IjvulPiUnWWiPx-D5Q/edit#

### PR DESCRIPTION
**Pull request by miaerbus**
Fixes #28 

- [X] content needs to be added to https://backend.sledilnik.org/admin/

### CODE REVIEW

**Comment by jalezi** [comment]
I can convert but need some content and maybe a few days.

**Comment by lukarenko** [comment]
I have added the right backend and entered some FAQ entries. We need to figure out how to present tables and list, as they are not supported or do not look nice. 
image

**Comment by miaerbus** [comment]
Thanks for adding content. I fixed the table by adding a line of hyphens after heading, like this: https://www.markdownguide.org/extended-syntax/#tables

**Comment by miaerbus** [comment]
I disabled language detection because it doesn't resolves to the correct language when I hit the root url (for me it resolves to 'en-GB'). Also added lazy loading of pages as @mihaerzen suggested in my older PR.

**Comment by lukarenko** [comment]
I have copied all of FAQ content and hopefully resolved most issues.

@miaerbus Is it possible to support markdown also in tooltips? 
image

Some markdown is used in glossary and makes sense. 
image

**Review by lukarenko — APPROVED** [review]

**Comment by lukarenko** [comment]
Will merge, we can improve tooltip later

**Pull request merged**
