### PR TITLE
fix(DoctorPage): ✨ doctor with multiple phone nums

### PR DESCRIPTION
**Pull request by jalezi**
Creates new component <PageInfoPhones/>

FIX: #127

Not quite sure but maybe is better to merge this one before #149.

### CODE REVIEW

**Comment by lukarenko** [comment]
@jalezi it is fine on Doctors page, but the icon on Tooltip and Card still tries to call two numbers.
I suggest we only put the first number on the icon.
image

**Comment by jalezi** [comment]
I haven’t touched Home page, yet.

**Review by lukarenko — APPROVED** [review]
Looks OK to me. 
@jalezi Can we merge (still marked as Draft)?

**Comment by jalezi** [comment]
@lukarenko just wait for @bananica to check the https://github.com/sledilnik/zdravniki/pull/150/commits/6052de80e3301b0d0bfc3612718bd78a1ba4c596. 
I guess if no phone num, button should be disabled.

**Comment by lukarenko** [comment]
@jalezi OK
BTW, can you improve spacing between www and phone - on mobile it is hard to touch the right one due to fat fingers
image

**Comment by jalezi** [comment]
@bananica please pay attention on https://github.com/sledilnik/zdravniki/pull/150/commits/4ed1cb9f26f21eaa22d0cf0dae55f7815b666a29. Can we remove?

**Comment by jalezi** [comment]
Closed due to ugly git history. I will create new PR.

**Pull request closed without merging**
