### PR TITLE
i18n: Enabled Croatian translation

### PR DESCRIPTION
**Pull request by stefanb**
Translation:  [Stanje prevoda](https://hosted.weblate.org/projects/sledilnik/zdravniki/hr/)
https://hosted.weblate.org/projects/sledilnik/zdravniki/hr/

Needs finishing and review.

Preview: https://pr-446.zdravniki.sledilnik.org/hr/

cc @vekejsn 

Related:
* #193 
* #208

### CODE REVIEW

**Review by jalezi — APPROVED** [review]
There is full stop after year. Otherwise looks good

full stop after year

**Review by kesma01 — APPROVED** [review]
Seems OK.

**Comment by vekejsn** [comment]
> There is full stop after year. Otherwise looks good
> 
> full stop after year

The dot is placed there according to the datetime locale, and is ok to be there.

**Comment by stefanb** [comment]
We have the dot also on https://covid-19.sledilnik.org/hr/stats :
image

**Comment by stefanb** [comment]
I thought we have plural forms enabled from before, but apparently we don't.

**Comment by stefanb** [comment]
Seems better after b2c90584da48b9c77464bf376f4a40c358d8855d:

image
image
image

**Review by jalezi — APPROVED** [review]
LGTM

**Pull request merged**
