### PR TITLE
Favicons & tw/fb share card image

### LINKED ISSUE #26: Favicon and icon for social media
We need favicon and green icon for social media (square, no text)
image

image

### PR DESCRIPTION
**Pull request by bananica**
resolves #26

### CODE REVIEW

**Review by stefanb — APPROVED** [review]

**Comment by stefanb** [comment]
BI za social preview / opengraph image bil bolj primeren nek screenshot, lahko pomanjšan / zamegljen / prekrit z logotipom?
image

**Comment by bananica** [comment]
We can change it, in that case I would wait until the page is a bit more polished, or we could use design image as a "screenshot"

**Comment by bananica** [comment]
Btw. question, will `PUBLIC_URL` be set to protocol + host once the page is published? Since share photos (tw/fb) must be an absolute URL (with protocol + hostname)

**Comment by stefanb** [comment]
yes, whatever it takes.

**Pull request merged**
