### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by bananica**
I've done some changes based on the last design. Not everything unfortunately, for example mobile view with collapsable filter drawer and view type switching is missing. 
Somebody should probably take a look at the code since I'm a react noob.

The page looks like this ATM:
CleanShot 2021-12-08 at 03 17 11
CleanShot 2021-12-08 at 03 17 45

### CODE REVIEW

**Comment by jalezi** [comment]
@overlordtm how far are you with PR preview?

@bananica it looks awesome!

I'm just not sure if infinite scroll is working on all breakpoints or just back to top button is not visible.
Drawer (sidebar) has lost transition unless is on purpose and I guess you hate scrollbar style :).

Also we need to change colour (links) in Faq and About but this can wait while @miaerbus and I separately made some changes in Faq and About. See: #82.

There are already some not style related changes in Accepts component #81 (https://github.com/sledilnik/zdravniki/pull/81/commits/f7f4543cd5f41327b4fbc0f8a3fd19e0201b4b48) and in #83.
Probably speaking from my inexperience but I have minor "git bomb" in my head.


Here is also missing attribution #86 while on next breakpoint is visible. My poor attempt to solve it is in #88.
desktop-bananica-001

desktop-sm-bananica-001

tablet-bananica-001

tablet-old

**Comment by bananica** [comment]
@jalezi thanks ;)

Back to top on mobile is not visible atm, it's hidden bellow filter.
Drawer on mobile works just fine for me, it's just a bit faster (it was so slow before), tried it in chrome and safari. Anybody else not seeing drawer transition?

Scrollbar - I just think it's better to leave it to OS :) But if everybody else prefer it styled and always on (mac/ios hides scrollbar when not scrolling/interacting with it) we can change it back.

I forgot about FAQ/About us, my bad :(

As for mobile, I think it would be great if we had something like this:
PixelSnap 2021-12-08 at 14 10 48

But I think I'll need some help with it, for example with this display of selected filters:
PixelSnap 2021-12-08 at 14 11 32

And maybe with this view type switcher:
PixelSnap 2021-12-08 at 14 11 51

Maybe just a point in the right direction, how to solve these two.

**Comment by jalezi** [comment]
> Drawer on mobile works just fine for me, it's just a bit faster (it was so slow before), tried it in chrome and safari. Anybody else not seeing drawer transition?

Ok. It's just faster. I kind a like slower, just my preference. Not important.

Definitely I would go we your mobile design. I hate huge filter on mobile.

One mistake that I have made earlier when I was first changing design that I made AppBar component static. I am quite sure that it will be better if Header is always visible when it doesn't scroll with content (Faq and About)

**Comment by jalezi** [comment]
Also on desktop it's very hard to change language. :)

lang-desktop

**Comment by jalezi** [comment]
> I would probably try to use [complex-interaction](https://mui.com/components/cards/#complex-interaction), only collapsible part (CardActions and Collapse). I guess Filters component will be inside Collapse and with [breakpoint-helpers](https://mui.com/components/use-media-query/#using-muis-breakpoint-helpers) I would try to control whether CardActions are visible or not.

@bananica [here](https://github.com/sledilnik/zdravniki/tree/feat/blue-design) is an example. I have created new branch from this PR.

**Comment by jalezi** [comment]
> I guess this one is almost the same as Filters/ToggleAccepts (based on ToggleGroup) only handling different state.
> 
> In /components/Doctors we need to set state which will be passed to new switcher and conditionally show either map or cards. And then we have to figure out how to show everything on tablet and up. The problem is that ToggleGroup is "exclusive".

@bananica now I added also map/cards toggle on [branch](https://github.com/sledilnik/zdravniki/tree/feat/blue-design ) in https://github.com/sledilnik/zdravniki/commit/d04915fd76d8c2581791247baee0759ff796e94b.

It's not perfect but it will do.

**Comment by stefanb** [comment]
Since #93 was merged please check if everything was ported over to branch [develop-blue-design](https://github.com/sledilnik/zdravniki/compare/develop-blue-design) and continue there.

**Comment by bananica** [comment]
I think we can close this one, as far as I can see everything is ported to the `develop-blue-design`

**Pull request closed without merging**
