### PR TITLE
Mobile seach gap

### PR DESCRIPTION
**Pull request by mitjapotocin**
Before:
image

After: 
image

### CODE REVIEW

**Comment by stefanb** [comment]
Minor nitpick: Search box is not stretching enough to fill the space on tablets, not sure if this is on purpose or not.

Ipad:
image

Surface duo
image

**Comment by jalezi** [comment]
> Minor nitpick: Search box is not stretching enough to fill the space on tablets, not sure if this is on purpose or not.

@stefanb Long story :). Would you prefer to fill the space?

**Review by jalezi — APPROVED** [review]

**Comment by stefanb** [comment]
> > Minor nitpick: Search box is not stretching enough to fill the space on tablets, not sure if this is on purpose or not.
> 
> @stefanb Long story :). Would you prefer to fill the space?

Not necessarily, maybe only if it takes less than a few seconds to do so reliably 🙂

**Comment by jalezi** [comment]
> > > Minor nitpick: Search box is not stretching enough to fill the space on tablets, not sure if this is on purpose or not.
> > 
> > 
> > @stefanb Long story :). Would you prefer to fill the space?
> 
> Not necessarily, maybe only if it takes less than a few seconds to do so reliably 🙂

@mitjapotocin can you? I have tried once.

**Review by stefanb — APPROVED** [review]

**Comment by stefanb** [comment]
Wonderful!
Can we stretch it also on desktop?
image

**Comment by lukarenko** [comment]
Merged. Can imrove desktop nitpick later

**Pull request merged**
