### PR TITLE
Report error improvements

### LINKED ISSUE #94: Report error improvements
- [ ] Input fields validation
- [ ] we should probably add icon (maybe a flag 🏴 by @bananica) on search result. When clicked, we could simply open doctor page in report error mode.
- [ ] I would add free-form entry of additional Note where user can write freely what is wrong. For example "doctor is currently on maternity leave and does not accept patients"
- [ ] if we have Flag to report problem on each search results, then we can remove Prijavi napako from navigation bar
- [ ] we need type of doctor in the form results, as some doctors are working in multiple setups (adults and youth)

### PR DESCRIPTION
**Pull request by miaerbus**
Fixes #94 and #95

Apologies again for a huge PR, I can split it into two parts if necessary.

@bananica I'd put the report error icon to the top right aligned with doctor's name on both places (doctor card and doctor page), what do you think? Maybe you can also create a better icon if you have time.

@lukarenko I tried accessing the [new google form](https://docs.google.com/forms/d/e/1FAIpQLScTtkvuHEtvcD1dlcwdJ5hQbhLkOZv0dOM8797eJvd0PkKdlQ/viewform?usp=sf_link) but I still can't access it. You edit `.env` file and replace all the variables starting with `REACT_APP_GOOGLE_FORM_*` with the new values that can be found by adding `/prefill` to the url. Inspect the fields and copy the number from the `name` attribute (without `entry.`):
howto

### CODE REVIEW

**Comment by miaerbus** [comment]
@lukarenko I have the access now, just didn't see the email before. I'll add the necessary.

**Comment by jalezi** [comment]
@miaerbus ahh, I fixed one and produce another bug.

**Comment by lukarenko** [comment]
@miaerbus looks good to me. Maybe we just need better icon from @bananica and check that it merges with new blue design. 
Icon also need better tooltip: "Prijavi napako v objavljenih podatkih"

**Comment by lukarenko** [comment]
@miaerbus another enhancement: can we add some text on top, to make it clear that you are in edit mode and can suggest changes to shown data:
**Prijavi napako na posameznih podatkih o zdravniku in vnesi pravilne podatke ali opombo:**
Mogoče v bold nad edit polja?
image

**Comment by miaerbus** [comment]
Right now it looks there aren't that many conflicts.

Just one more thing that bothers me - routes. We have it now all mixed up right now, like this:
- /faq
- /about
- /zdravnik/{priimek-ime}
- /zdravnik/{priimek-ime}/edit
- /ginekolog/{priimek-ime}
- /ginekolog/{priimek-ime}/edit
- ...

In sledilnik, we use English names only but I'm not sure if that's ok here.

**Comment by lukarenko** [comment]
@miaerbus Can we also add URL to doctor page to form fields? That way we can directly click URL from form results to inspect the data of doctor.

**Comment by lukarenko** [comment]
@miaerbus I would switch to english names too or even better to doctor type ID (gp, gp-y, gyn).

**Comment by miaerbus** [comment]
Would it be better if I put the 'report error' icon on top? What about the doctor's page?

yay-or-nay

**Comment by lukarenko** [comment]
It is for @bananica to decide

**Comment by bananica** [comment]
Maybe if we merge it first and then I'll try to come up with something (it doesn't look bad as it is btw).  
Maybe if we show it on hover (on desktop)?

**Comment by jalezi** [comment]
> Would it be better if I put the 'report error' icon on top? What about the doctor's page?
> 
> yay-or-nay

On top, definitely.

InkedScreenshot 2021-12-17 06 08 19_LI

**Comment by jalezi** [comment]
@miaerbus If user navigates to `edit` path and `cancel` (haven't tried `send` but I assume is the same) he still stays on `edit` path. Similar issue if he starts on doctor's page and goes to edit mode. It does not navigate to `edit` path.

Maybe instead of `edit` should be `report-error` path.

**Comment by jalezi** [comment]
> Maybe if we merge it first (blue design to master)

@miaerbus @bananica @stefanb Which PR should we merge first? #100 or #102?

**Pull request merged**
