### PR TITLE
fix(Home): 💄 zoom and filter state lost

### PR DESCRIPTION
**Pull request by jalezi**
only mobile view (down md)
before:
map & cards are un-mounted when switching between views.

after:
use css (opacity) to show different view
! zIndex must change -> map events issue (not quite sure about it)

### CODE REVIEW

**Comment by jalezi** [comment]
todo: fly to doctor from cards view

**Comment by bananica** [comment]
This looks and works great on mobile

**Review by bananica — APPROVED** [review]

**Comment by lukarenko** [comment]
@jalezi this is great - can we merge?

**Comment by jalezi** [comment]
jp

**Pull request merged**
