### PR TITLE
Map marker cluster color should be informative

### PR DESCRIPTION
**Pull request by bananica**
- Map marker cluster color should be based on the % of doctors who accept new patients
- Green 100% if all doctors accept, red none do, and 3 shades in between (25, 50, 75%)
- Round it to 25% so there's not too much shades
- Up to 25% color even if just 1 doctor accepts
- Down to 75% color even if just 1 doctor does not accept

I tried first with light text on darker cluster colors, atm all are dark, here are screenshots of both.
Comments welcome.

PixelSnap 2022-01-04 at 23 30 55

PixelSnap 2022-01-04 at 23 37 30

### CODE REVIEW

**Comment by lukarenko** [comment]
@bananica This is great. I only have two suggestions:

100% accepts or rejects should be shown in the same color as single point. This is the case for red, but not for green:
image
image


I would also make >50% available more optimistic (at least green). Cluster with 50+ accepting is not very common and should be at least light green. We should use yellow, orange and red all for "alert" colors and rather show how bad the situation is for cases where most of doctors are not accepting.
image
image

**Comment by bananica** [comment]
@lukarenko I agree ... as for the optimistic color tweaks, maybe like this: 


PixelSnap 2022-01-05 at 09 48 28

**Comment by lukarenko** [comment]
@bananica this is much better. Can we change single doctor color to match cluster color of all accepts or all rejects? It still looks lighter in cluster and somehow confuses me to think that some green doctor might be hidden somewhere.
image

**Comment by bananica** [comment]
@lukarenko this is because of the opacity, I'll try to tweak it a bit later

**Review by lukarenko — APPROVED** [review]
Just merge

**Review by jalezi — APPROVED** [review]

**Pull request merged**
