### PR TITLE
Doctor card buttons => dropdown menu with labels

### PR DESCRIPTION
**Pull request by bananica**
To avoid cramped buttons on small screens move everything to the menu, this way we can add some more actions in the future.
Make the rest of the card clickable (go to DR page)
Report error icon changed
PixelSnap 2021-12-22 at 00 26 55

### CODE REVIEW

**Comment by stefanb** [comment]
The functionality is hidden into the menu also on large screens, not sure if this is desirable
User has to open the menu to see if the doctor has a phone
"Show on map" isn't working anymore
Doctors card are not accessible as links anymore (SEO #91 / #99, right click copy link address, open link in new tab...)

**Comment by lukarenko** [comment]
I think Phone should not be in menu, but always shown if available.

**Comment by bananica** [comment]
I moved the phone btn outside of the menu so it's always visible.
SEO should be ok now, the whole left side of the card is wrapped with <a>

**Comment by lukarenko** [comment]
@bananica this looks great! Can you rebase to master to include new tooltip from @miaerbus and also apply simplification there? I would suggest that we do not have menu there, but just phone + link to doctors card

**Comment by bananica** [comment]
@lukarenko I merged from master into this branch and also from @miaerbus tooltips/popups so it's all included and it (probably) can be safely merged into master. 
Popups look like this at the moment, we can remove menu completely if you think there's no need for it:
PixelSnap 2021-12-22 at 10 40 45

**Pull request merged**
