### PR TITLE
added dockerfile

### PR DESCRIPTION
**Pull request by overlordtm**
First step, actions come tomorrow (or later today)

### CODE REVIEW

**Comment by stefanb** [comment]
So far it builds! 🚀

**Review by stefanb — APPROVED** [review]
Caddy also serves the website nicely!

**Comment by stefanb** [comment]
@overlordtm do you want to add something else here or will the actions be in a separate PR (to be merged after the repo is transferred)?

**Comment by overlordtm** [comment]
This can be merged, actions come in another PR

**Review by stefanb — APPROVED** [review]

**Pull request merged**
