### PR TITLE
Search for name no mather the order

### LINKED ISSUE #191: Search: "first last" should work the same as "last first"
Currently it seems that search looks for exact order as in the listed name of doctor (last first). Search should always find doctor by name even if order is changed.

image

### PR DESCRIPTION
**Pull request by mitjapotocin**
Fixes #191

### CODE REVIEW

**Comment by stefanb** [comment]
Searching for "Ana marija" matches also a single word "Marijana"

**Comment by mitjapotocin** [comment]
Should work now

**Comment by mitjapotocin** [comment]
Will do a smal refactor and optimizatoin in the afternoon ⛷

**Comment by jalezi** [comment]
> Will do a smal refactor and optimizatoin in the afternoon ⛷

Sorry, I didn't see.
I just removed lint errors.

**Comment by stefanb** [comment]
I cherry-picked 🍒 unrelated linter warning fixes by @jalezi to `master` branch, to have them everywhere ASAP and not to clutter the diff of this PR.

**Comment by lukarenko** [comment]
@mitjapotocin this is great!

**Comment by mitjapotocin** [comment]
@jalezi pls check and merge at will

**Review by jalezi — APPROVED** [review]
Perfect.

**Pull request merged**
